### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michelerobertazzi** [mochman/Bypass_CGNAT#11]
Internet doesn't working on the homeserver after putting on the VPN but if i ping 10.0.0.1 (VPS IP) I get a response

**Comment by mochman** [comment]
Fill this out.

**Describe the problem**
A clear and concise description of what the problem.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Script Version**
If using the automated script, which version?

**VPS wireguard config (/etc/wireguard/wg0.conf)**
*Please clear out all public IPs and Public/Private Keys*

**Local Server wireguard config (/etc/wireguard/wg0.conf)**
*Please clear out all public IPs and Public/Private Keys*

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by michelerobertazzi** [comment]
I resolved the problem thank you!
